# Generated by Django 5.1.7 on 2025-04-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
