# Generated by Django 5.1.7 on 2025-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_areaatuacao_remove_freelancer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_agendamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_servico',
            field=models.CharField(choices=[('imediato', 'Imediato'), ('agendado', 'Agendado')], default='imediato', max_length=20),
        ),
    ]
