# Generated by Django 5.1.7 on 2025-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_atualizar_status_aceito'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='metodo_pagamento',
            field=models.CharField(choices=[('stripe', 'Cartão de Crédito/Débito'), ('multibanco', 'Multibanco'), ('transferencia', 'Transferência Bancária'), ('paypal', 'PayPal')], default='stripe', max_length=50),
        ),
        migrations.AddField(
            model_name='fatura',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='stripe_payment_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
