# Generated by Django 5.1.7 on 2025-04-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_comentario_avaliacao_comentario_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='google_calendar_event_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
