# Generated by Django 5.1.7 on 2025-04-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0009_pedido_google_calendar_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem', 'Nova Mensagem'), ('pedido', 'Novo Pedido'), ('aceitacao', 'Pedido Aceite'), ('rejeicao', 'Pedido Rejeitado'), ('conclusao', 'Serviço Concluído'), ('pagamento', 'Pagamento Recebido'), ('sistema', 'Notificação do Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
