# Generated by Django 5.1.7 on 2025-04-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0011_servico_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='servicos/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='autenticacao.servico')),
            ],
            options={
                'verbose_name': 'Imagem do Serviço',
                'verbose_name_plural': 'Imagens dos Serviços',
                'ordering': ['ordem'],
            },
        ),
    ]
