# Generated by Django 5.1.7 on 2025-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0012_servicoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
