# Generated by Django 5.1.7 on 2025-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0013_fatura_paypal_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='paypal_payment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='paypal_recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='stripe_application_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='stripe_connected_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_freelancer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor líquido para o freelancer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_plataforma',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado pela plataforma (taxa)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='freelancerdetalhe',
            name='paypal_account_verified',
            field=models.BooleanField(default=False, verbose_name='Conta PayPal Verificada'),
        ),
        migrations.AddField(
            model_name='freelancerdetalhe',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email PayPal'),
        ),
        migrations.AddField(
            model_name='freelancerdetalhe',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taxa da Plataforma (%)'),
        ),
        migrations.AddField(
            model_name='freelancerdetalhe',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Conta Stripe'),
        ),
        migrations.AddField(
            model_name='freelancerdetalhe',
            name='stripe_account_verified',
            field=models.BooleanField(default=False, verbose_name='Conta Stripe Verificada'),
        ),
    ]
