# Generated by Django 5.1.7 on 2025-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0014_fatura_paypal_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('mensagem', 'Nova Mensagem'), ('pedido', 'Novo Pedido'), ('aceitacao', 'Pedido Aceite'), ('rejeicao', 'Pedido Rejeitado'), ('conclusao', 'Serviço Concluído'), ('pagamento', 'Pagamento Recebido'), ('sistema', 'Notificação do Sistema'), ('proposta', 'Nova Proposta')], max_length=20),
        ),
    ]
